spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: ${MYSQL_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${MYSQL_ADDR:ENC(IG+MCcXYlC/7ZXAcMW0//4p+a3+0eaFptuvtY5Ot5KMjwuAIhxcBE4CGnOBWq1/mI6WZoKTBcmAR2a9LbyMXjCRkQgvCK85dKwhuPtT6pa+BEsQNh2LKHW5UDZRQqD9N55yjpeSUocLHYmLfywZbgDhdO3DAJrOC)}
    username: ${MYSQL_USERNAME:ENC(O0WJdHK10k6bhTSQJbTEGrsBytLKSmRX)}
    password: ${MYSQL_PASSWORD:ENC(xk8u9sk/O8iQp5hULhWtASCPvSC6R5o+AggfXiITFKR7iA8kGncdzw==)}
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: ${REDIS_ADDR:ENC(gfVHUx9Q3MOobwxRYtxbvNuo0SeQBllfb7SLgEtm8ZY=)} # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: ${REDIS_PORT:ENC(lFAbKYtMOt5dctRhoYYeIdekCwPv5euR)} # Redis服务器连接端口
    password: ${REDIS_PWD:ENC(g+DlVpnt76Ji9s86jd28sGrL+GMWgvWivTRehbesgrA=)} # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:ENC(VdzZDIUI6EP3mXnpOmb0l46RpSA5HlJgqy9/ZxU0Mx3U777m+o9J6Q==)}
      username: ${NACOS_SERVER_USER:ENC(qqqHXA1bwhhYPJ9SXXZqyO5j//wygYDK)}
      password: ${NACOS_SERVER_PASSWORD:ENC(v1J0g/bB0xWCi9Te8mwH1o309G9xtm6q1L8SeCkYdYY=)}
      config:
        file-extension: yaml
      discovery:
        ip: ${SERVER_ADDR:ENC(Y5HcvI+7TfzJVRmAMpYDqR0bwJqzwMzdpQ8RCIr1y2w=)}
  application:
    name: file-system-service${UNIQUE_ID:0}
aliyun:
  oss:
    endpoint: ${ALIYUN_ENDPOINT:ENC(Nq/ROzXCH519HvbCkIsPkeWiC5gtYt62YZCv/B1bQ9CyWQXYWAFfv666Z+YlYoz4uCHT0aJsiOlu0dceHJH4GSJROM1ZG7/5)}
    accessKeyId: ${ALIYUN_ACCESSKEYID:ENC(l0Fm2Kk2H3SuMqxBH51mYz0IYUnbQ5p0ZmfieytKx6YMh1TmqFmeTk1ExyT2blCR)}
    accessKeySecret: ${ALIYUN_ACCESSKEYSECRET:ENC(ISX5rMzRdZHDDH5wsdMe0dwPTmkH2xSAm39iTUt695IXegXV+kdcpkeFOR6suHgb)}
    bucket: ${ALIYUN_BUCKET:ENC(xjUC5boRO8KFBwSs6uq7IDk1ZlwMOZ5ORqxlHliziyQ=)}
    bucket-private: ${BUCKET_PRIVATE:ENC(FhyRfhTLHOBYkWbGeOsUlAG3UD5EaiFG/YEfYyCGb50=)}
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ${JASYPT_PASSWORD:}
oss:
  handler: ${OSSHandler:aliyun}
